### ISSUE TITLE
Channel separation/4-channel playback?

### ISSUE THREAD

**Issue by TheEssem** [8bitbubsy/ahx2play#2]
Just found this project, it seems very promising. I was wondering if it's possible to separate each track/channel into separate channels or WAV output files, since there doesn't seem to be a very good way to handle this for AHX tunes at the moment. Currently the only convenient way to do this is with [a fork of UADE by 4irmann](https://blog.airmann.de/uade-multichannel-audio-support/) which adds a `--quadmode` option; however, the AHX eagleplayer included with UADE is somewhat inaccurate and plays some tunes ([example](http://modland.com/pub/modules/AHX/Syphus/last%20tense%20(2nd%20version).ahx)) incorrectly.

See also: https://github.com/pete-gordon/hivelytracker/issues/44

**Comment by 8bitbubsy** [comment]
That's not a feature that I think is needed in a standalone replayer. The muting logic is not implemented.
However, look out for an AHX clone in the future (not anytime soon), where I will make sure muted channels are not rendered when rendering to WAV.
