### ISSUE TITLE
Odd D00 jumping.

### ISSUE THREAD

**Issue by pachuco** [8bitbubsy/ahx2play#3]
Not sure how original AHX behaves, but this tune is suspicious.
It loops on itself in pos 000.

[i've been indoors more than once.zip](https://github.com/8bitbubsy/ahx2play/files/7686810/i.ve.been.indoors.more.than.once.zip)

**Comment by 8bitbubsy** [comment]
Will look at this in a couple of days.

**Comment by 8bitbubsy** [comment]
This has been fixed. It was a porting error in the Dxx effect. Apparently the 0xx effect (set hi-byte for position jump) is just for position jump, and not for pattern break. Makes sense.
